import cv2
import pyautogui

pyautogui.FAILSAFE = False


#pre-trained classifiers to detect face and eyes
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)
eye_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_eye.xml"
)


#for opening webcam
cam = cv2.VideoCapture(0)                 #default webcam=0
screen_w, screen_h = pyautogui.size()     #screen_w,screen_h=monitor resolution[maps eye-screen position]

while True: #checks frames generated by webcam
    ret, frame = cam.read() #ret=whether frame was captured successfully,frame=actual image 
    if not ret:
        break


#read and prepare camera frame
    frame = cv2.flip(frame, 1) #flips mirror image(movement becomes natural )
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)


#face detection
    faces = face_cascade.detectMultiScale(gray, 1.3, 5) #1.3=scale factor(how much image size reduces each scan),5=minimum neighbours(higher for stricter detection)


#looping through the detected faces
    for (fx, fy, fw, fh) in faces:
        roi_gray = gray[fy:fy+fh, fx:fx+fw] #roi=region of interest
        roi_color = frame[fy:fy+fh, fx:fx+fw]


#detection of eyes
        eyes = eye_cascade.detectMultiScale(roi_gray)

#through one eye and detecting eye center
        for (ex, ey, ew, eh) in eyes[:1]:#converts eyes position to full frame coordinates,cx,cy=center of each x and y
            cx = fx + ex + ew // 2
            cy = fy + ey + eh // 2


#map eye position to mirror cursor position on the screen
            pyautogui.moveTo(#core mouse movement logic
                int(cy / frame.shape[1] * screen_h)
            )


#draw rectangles around eye
            cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh), (0,255,0), 2) #gives visual feedback(green colour)

            # Blink detection 
            if eh < 15:
                pyautogui.click()
                print("Clicked")


#display window
    cv2.imshow("Eye Controlled Mouse (Python 3.14)", frame) #shows webcam feed,face and eye boxes


#exit on esc key
    if cv2.waitKey(1) & 0xFF == 27: #27=esc key
        break

#cleanup
cam.release()
cv2.destroyAllWindows()




